RESULT = parseDotTestProgram
SOURCES = \
  src/DecisionTree.ml \
  src/TreeClassifier.ml \
  test/ParseDotTest.ml
  
LIBS = ocamlgraph/*

PACKS = ocamlgraph Str
  
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)